### ISSUE TITLE
Hello...BeagleBone Black and Daffodil USB Sound Adapter/Seth

### ISSUE THREAD

**Issue by silver2row** [opensrc/alsa#12]
Hello Again,

This is Seth. I am trying to make a bot. I know you could care less but I am using alsamixer to promote sound. I tried to play a .wav file with a Daffodil USB Sound Adapter. I could only get voice input. I could not get any voice/music output.

The speaker works and the Daffodil USB Sound Adapter says on and I get feedback but no music. 

I was wondering if anyone else brought up this complication. Is alsamixer having trouble with some USB configurable devices? I do not want to blame the alsamixer or the BBB but I configured with F6 via Ethernet and PuTTY on my BBB. 

If you could send some support, it would be very helpful. I am working out of the book, "BeagleBone Robotic Projects." The information, if you have the book, is on page 71 through page 73.

Sincerely,

Seth
![first on page 71](https://cloud.githubusercontent.com/assets/9708195/11113110/82e6d0a8-88df-11e5-9b3f-ef653dc465a3.JPG)
![page 72](https://cloud.githubusercontent.com/assets/9708195/11113111/82e7b1a8-88df-11e5-9c96-d6f78332d695.JPG)
![page 73 1](https://cloud.githubusercontent.com/assets/9708195/11113109/82e637ba-88df-11e5-9452-27badb3000ea.JPG)
![page 73](https://cloud.githubusercontent.com/assets/9708195/11113108/82e30180-88df-11e5-9cd9-cf3e5cf24763.JPG)
![second on page 71](https://cloud.githubusercontent.com/assets/9708195/11113112/82e7cd6e-88df-11e5-8c1a-4f401c90f90c.JPG)

**Comment by silver2row** [comment]
Hello Again,

This is Seth. I just updated my OS/Linux Distro on my BBB. I will see if this works. If not, I will come back to see if there were any recommendations. 

Sincerely,

Seth

**Comment by silver2row** [comment]
Hello Again,

I tried the update on Debian Jessie. I updated and upgraded. I still cannot get the Daffodil USB Sound Adapter to work with alsamixer. If you have any suggestions, please let me know.

Sincerely,

Seth

**Comment by markc** [comment]
I use the latest kubuntu with a focusrite USB device and it took me a month to get it working correctly. Now it's just on all the time and always there after a reboot via Jack and pulseaudio. The main thing is to `tail -f /var/log/syslog` (or whatever the main system logfile is) while you plug the device in to confirm it's being detected and then to use `aplay -l` to get some idea of what device it is. In my case using `alsamixer` then F6 to see all the audio devices then selecting my USB drive and simply UNMUTING the master and headphone outputs was a critical part of my USB audio device journey.

Maybe some clues here might help...

http://www.cpmspectrepi.webspace.virginmedia.com/raspberry_pi/MoinMoinExport/DaffodilUSBSoundAdapter.html

**Comment by silver2row** [comment]
Thank you, sir. I will check it out. I will get back to you.

**Comment by silver2row** [comment]
Hello Mr. Mark,

I will check it out further. I briefly brushed over the site earlier. I need to sink my hands deep into its heart to fix the issue, maybe. Who knows? I will just keep trying. Thank you for your support. 

Sincerely,

Seth

P.S. I updated my Wheezy to a 4GB Jessie today. Hopefully, this will do the trick of tricks.

**Comment by silver2row** [comment]
I found that I can play 8bit sound on my headphones but I think it is distorted because of the external sound on my headphones. I am still working with the software and hardware. 

Oh and the software works. I will keep up the work on it to provide me, selfishly, with some output/input. Thank you again...

Sincerely,

Seth
