### ISSUE TITLE
Adobe flash firefox audio issue.

### ISSUE THREAD

**Issue by mr-blobbyyy** [opensrc/alsa#25]
- issue may have been present before the [flashplugin 27.0.0.130-1](https://www.archlinux.org/packages/extra/x86_64/flashplugin/) update but I just noticed it today after updating yesterday.

- issue: a flash stream is playing audio in firefox. while streaming, open another audio source (such as vlc or audacious) which doesn't play audio and this is logged:
`pulseaudio[x]: E: [alsa-sink-USB Audio] alsa-sink.c: Error opening PCM device front:2: Device or resource busy`

- the reverse is true: vlc or audacious is playing and when attempting to play a flash stream in firefox, the video is fine but there is no audio on the stream. either nothing is logged or this is logged:
```
pulseaudio[x]: E: [alsa-sink-USB Audio] alsa-sink.c: ALSA woke us up to write new data to the device, but there was actually nothing to write.
pulseaudio[x]: E: [alsa-sink-USB Audio] alsa-sink.c: Most likely this is a bug in the ALSA driver 'snd_usb_audio'. Please report this issue to the ALSA developers.
pulseaudio[x]: E: [alsa-sink-USB Audio] alsa-sink.c: We were woken up with POLLOUT set -- however a subsequent snd_pcm_avail() returned 0 or another value < min_avail.
```

- issue is not reproduced in chrome (assuming this is an NPAPI (or firefox) issue since I also have **pepper-flash** installed.)

- issue is resolved once the stream is stopped or the browser tab is closed.

my device: FiiO e10k (inxi: GYROCOM C&C) usb headphone amp. xfce audio configuration recognizes it as "DigiHug USB Audio", set as "analog stereo output".

**Comment by markc** [comment]
I'm sorry but I can't help you with this particular problem. I'm sure the folks at alsa-dev would be interested in a potential alsa bug, if one exists, or may be able to suggest a solution...

http://mailman.alsa-project.org/mailman/listinfo/alsa-devel

**Comment by synthor** [comment]
Hey folks,

quite funny catch here. I was wondering why the adobe-flashplugin of the Canonical partner program doesn't play audio in Firefox while it works in Chromium.

This afternoon I connected my Focusrite usb interface to my laptop and struggled with getting it to play sound first. I noticed this in the syslog

```
synthor@ubunthor:~$ sudo grep sink /var/log/syslog
Oct  6 17:15:30 ubunthor pulseaudio[15954]: [alsa-sink-USB Audio] alsa-util.c: Got POLLNVAL from ALSA
Oct  6 17:15:30 ubunthor pulseaudio[15954]: [alsa-sink-USB Audio] alsa-util.c: Could not recover from POLLERR|POLLNVAL|POLLHUP with snd_pcm_prepare(): Kein passendes Gerät gefunden
Oct  6 17:21:04 ubunthor pulseaudio[3332]: [alsa-sink-USB Audio] alsa-util.c: Got POLLNVAL from ALSA
Oct  6 17:21:04 ubunthor pulseaudio[3332]: [alsa-sink-USB Audio] alsa-util.c: Could not recover from POLLERR|POLLNVAL|POLLHUP with snd_pcm_prepare(): Kein passendes Gerät gefunden
Oct  6 22:23:32 ubunthor pulseaudio[3332]: [alsa-sink-USB Audio] alsa-sink.c: ALSA weckte uns auf, um neue Daten auf das Gerät zu schreiben, doch es gab nichts zum Schreiben!
Oct  6 22:23:32 ubunthor pulseaudio[3332]: [alsa-sink-USB Audio] alsa-sink.c: Dies ist höchstwahrscheinlich ein Fehler im ALSA-Treiber 'snd_usb_audio'. Bitte melden Sie diesen Fehler den ALSA-Entwicklern.
Oct  6 22:23:32 ubunthor pulseaudio[3332]: [alsa-sink-USB Audio] alsa-sink.c: Wir wurden durch das POLLOUT-Set geweckt, allerdings lieferte ein anschliessender snd_pcm_avail() den Wert 0 oder einen anderen Wert < min_avail.
```

After pulseaudio -k the Focusrite works as usual.

Maybe there's a connection between those bugs? I was wondering about weird problems the last days which never ocurred before in years.

**Comment by mr-blobbyyy** [comment]
@synthor the problem is with Adobe's 27.0.0.130-1 update. They introduced new "sound features" that messes with usb audio installs. Chromium and Chrome have different sound APIs so these are not affected -- only NPAPI installs are affected. Adobe has said they plan to release a new version on the 10th which reverts sound changes to version 26-levels (but expect another week probably to see it finally appear in your favourite repo.) NPAPI has long been criticized as being slow, buggy, and insecure (Mozilla's own words) so the day when Mozilla finally kills it off in 2020 can't come soon enough.

Closing.

**Comment by synthor** [comment]
Thx for all the info mate. Saves me a lot of wasted time spent searching for a solution.  :1st_place_medal:

**Comment by markc** [comment]
@mr-blobbyyy yes, good to know and thanks for your response, certainly beats my boilerplate "you'll have to ask on the alsa mailing-list" answer.
