### ISSUE TITLE
Website presents incorrect TLS cert

### ISSUE THREAD

**Issue by hairyhenderson** [opensrc/alsa#27]
Hi @markc - Looks like there's an issue with the TLS cert. When I visit http://alsa.opensrc.org/ I'm redirected to https://alsa.opensrc.org/ (which is great! TLS everywhere is 👍). However, the certificate that's presented is for `opensrc.org`, and not `alsa.opensrc.org`, and is not a wildcard cert (I see it's from Let's Encrypt, which [doesn't yet do wildcard certs](https://letsencrypt.org/2017/07/06/wildcard-certificates-coming-jan-2018.html)).

I was thankful to discover that all the docs are in markdown format in GitHub, so it's easy to just browse them here. But it would be handy to get the cert properly issued 😉

**Comment by markc** [comment]
Thank you for the heads up. For some dumb reason I decided to leave out the "alsa" subdomain last time I updated the certificate. Most docs were a quick crude conversion from Mediawiki to Markdown and some have been hand edited to remove extraneous gunk. Maybe 2018 will be the year I clean up the rest and remove a few dozen redundant pages.

**Comment by hairyhenderson** [comment]
Thanks for the quick response @markc!
