### ISSUE TITLE
xone23c mixer

### ISSUE THREAD

**Issue by molli1312** [opensrc/alsa#49]
Having a few problems with the Xone32c though not sure if this is an ALSA
issue or general USB stack problem.

It's a USB soundcard that is supposed to have 4 inputs and 4 outputs. It
seems to have 2 USB configurations (bNumConfigurations : 0x2). When plugged
in, bConfigurationValue is 0x1 and only 2 inputs and 2 outputs show up.
Change this value to 0x2 and it shows up (as it should) as 4 inputs and 4
outputs.

I can change the bConfigurationValue with this udev rule, or with a `echo 2

/sys/bus/usb/devices/1-1.4/bConfigurationValue`:

This has all been working OK on Ubuntu 20.04 running kernel
5.4.0-33-generic. However, I just updated to 5.4.0-37-generic and now there
is only a single USB configuration (bNumConfigurations : 0x1) and
bConfigurationValue can't be changed to 0x2:

**Comment by markc** [comment]
Looks like this got picked up here below, so hopefully someone will be able to advise you...

https://mailman.alsa-project.org/hyperkitty/list/alsa-devel@alsa-project.org/

**Comment by molli1312** [comment]
https://bugzilla.kernel.org/show_bug.cgi?id=217087
https://bugzilla.kernel.org/show_bug.cgi?id=217089
